---
env:
  browser: true
  es2021: true
  node: true
extends:
- eslint:recommended
- plugin:vue/essential
- plugin:@typescript-eslint/recommended
- "@nuxtjs/eslint-config-typescript"
parserOptions:
  ecmaVersion: latest
  parser: "@typescript-eslint/parser"
  sourceType: module
plugins:
- vue
- "@typescript-eslint"
rules:
  # single word component の許可
  vue/multi-word-component-names: 'off'
  # 複数ルートの許可
  vue/no-multiple-template-root: 'off'
  # 複数v-modelの許可
  vue/no-v-model-argument: 'off'
  '@typescript-eslint/no-unused-vars': 'warn'
  # html 属性の改行
  vue/max-attributes-per-line:
    - error
    - singleline:
        max: 3
      multiline:
        max: 1
  # 配列にカンマ強制
  comma-dangle:
    - error
    - only-multiline
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
